# Generated by Django 4.2.9 on 2024-03-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя события')),
                ('status', models.CharField(choices=[('active', 'активно'), ('completed', 'завершено'), ('canceled', 'отменено')], default='active', max_length=20, verbose_name='Статус события')),
                ('is_open', models.SmallIntegerField(choices=[(1, 'открытое'), (0, 'закрытое')], default=1, verbose_name='Статус')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата и время начала встречи')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Дата и время начала встречи')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Дата и время завершения встречи')),
                ('finish_time', models.TimeField(blank=True, null=True, verbose_name='Дата и время завершения встречи')),
                ('addr', models.CharField(max_length=255, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news_covers', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')),
            ],
            options={
                'verbose_name': 'Комментарий к встрече',
                'verbose_name_plural': 'Комментарии к встречам',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation', models.BooleanField(default=True, verbose_name='Поле для работы уведомлений приглашений')),
                ('status', models.CharField(choices=[('active', 'активно'), ('accepted', 'принято'), ('rejected', 'отказано'), ('canceled', 'отменено')], default='active', max_length=20, verbose_name='Статус приглашения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
            },
        ),
    ]
