# Generated by Django 4.2.9 on 2024-03-26 16:53

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя новости')),
                ('is_open', models.SmallIntegerField(choices=[(1, 'открытая'), (0, 'закрытая')], default=1, verbose_name='доступность новости')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время новости')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news_covers', verbose_name='Изображение')),
                ('views_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Просмотры')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Лайки')),
                ('is_published', models.SmallIntegerField(choices=[(1, 'опубликовано'), (0, 'на рассмотрении')], default=0, verbose_name='Опубликовано')),
                ('publishing_decision', models.SmallIntegerField(blank=True, choices=[(1, 'публиковать'), (0, 'отклонить')], null=True, verbose_name='Решение о публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')),
            ],
            options={
                'verbose_name': 'Комментарий к новости',
                'verbose_name_plural': 'Комментарии к новостям',
            },
        ),
        migrations.CreateModel(
            name='NewsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')),
            ],
            options={
                'verbose_name': 'Лайк к новости',
                'verbose_name_plural': 'Лайки к новости',
            },
        ),
    ]
