# Generated by Django 4.2.9 on 2024-03-26 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название турнира')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание турнира')),
                ('prizes', models.TextField(blank=True, null=True, verbose_name='Призы турнира')),
                ('start_date', models.DateField(verbose_name='Дата начала турнира')),
                ('finish_date', models.DateField(null=True, verbose_name='Дата окончания турнира')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')),
                ('participants', models.ManyToManyField(related_name='tournament_participants', to=settings.AUTH_USER_MODEL, verbose_name='Участники турнира')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
            },
        ),
        migrations.CreateModel(
            name='TeamTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.ManyToManyField(related_name='teamtournament_teams', to='players.team', verbose_name='Команда')),
                ('teams_games', models.ManyToManyField(related_name='teamstournament_games', to='games.teamgame', verbose_name='Номера игр')),
            ],
            options={
                'verbose_name': 'Командный турнир',
                'verbose_name_plural': 'Командные турниры',
            },
        ),
        migrations.CreateModel(
            name='SingleTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_games', models.ManyToManyField(related_name='singletournament_games', to='games.singlegame', verbose_name='Номера игр')),
            ],
            options={
                'verbose_name': 'Одиночный турнир',
                'verbose_name_plural': 'Одиночные турниры',
            },
        ),
        migrations.CreateModel(
            name='DoublesTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubles', models.ManyToManyField(related_name='doublestournament_doubles', to='games.doublesgame', verbose_name='Пара')),
                ('doubles_games', models.ManyToManyField(related_name='doublestournament_games', to='games.singlegame', verbose_name='Номера игр')),
            ],
            options={
                'verbose_name': 'Парный турнир',
                'verbose_name_plural': 'Парные турниры',
            },
        ),
    ]
