# Generated by Django 4.2.9 on 2024-03-26 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя клуба')),
                ('is_open', models.SmallIntegerField(choices=[(1, 'открытый'), (0, 'закрытый')], default=1, verbose_name='Статус')),
                ('addr', models.CharField(max_length=255, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('website', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Сайт')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clubs_logo', verbose_name='Логотип')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телеграмм')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
        migrations.CreateModel(
            name='ClubReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubreview_club', to='clubs.club', verbose_name='Заголовок отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
