# Generated by Django 4.2.9 on 2024-03-26 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('additions', '0001_initial'),
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubreview',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubreview_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_city', to='additions.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='club',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='club_game', to='games.game', verbose_name='Игры'),
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(related_name='club_members', to=settings.AUTH_USER_MODEL, verbose_name='Участники клуба'),
        ),
        migrations.AddField(
            model_name='club',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец клуба'),
        ),
        migrations.AddField(
            model_name='club',
            name='potential_members',
            field=models.ManyToManyField(blank=True, related_name='potential_club_members', to=settings.AUTH_USER_MODEL, verbose_name='Потенциальные участники клуба'),
        ),
    ]
